config/routes.rb
Rails.application.routes.draw do
  get 'pages/secret'
  get 'welcome/index'

  get '/login'     => 'sessions#new'
	
	# create (post) action for when log in form is submitted:
	post '/login'    => 'sessions#create'
	
	# delete action to log out:
	get '/logout' => 'sessions#destroy'  

  resources :employer
  
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employer.rb
class Employer < ApplicationRecord
    has_secure_password



    validates :name, length: { minimum: 2, 
    message: "should be atleast two characters" }

    validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

    validates :gender, format: { with: /\A[a-zA-Z]+\z/,
    message: "only allows letters" }

    has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    

    # Make the current_user method available to views also, not just controllers:
    helper_method :current_user
    
    # Define the current_user method:
    def current_user
        # Look up the current employer based on employer_id in the session cookie:
        @current_user ||= Employer.find(session[:employer_id]) if session[:employer_id]
    end

    # authroize method redirects user to login page if not logged in:
    def authorize
        redirect_to login_path, alert: 'You must be logged in to access this page.' if current_user.nil?
    end    
end

app/controllers/employer_controller.rb
class EmployerController < ApplicationController
    before_action :authorize, only: [:index]

    def index
        @employer = Employer.all
    end

    def show
        @employer = Employer.find(params[:id])
    end

    def new
        @employer = Employer.new
    end

    def edit
        @employer = Employer.find(params[:id])
      end

    def create
        @employer = Employer.new(logi)
 
        if @employer.save
            redirect_to @employer
        else
            #@employer.errors.each do |error|
                #flash[:errors] = error
            #end
            flash[:errors] = @employer.errors.full_messages
            redirect_to new_employer_path
        end
    end

    def update
        @employer = Employer.find(params[:id])
       
        if @employer.update(logi)
          redirect_to @employer
        else
          render 'edit'
        end
      end

    def destroy
        @employer = Employer.find(params[:id])
        @employer.destroy
        
        session.delete(:employer_id)
        redirect_to welcome_index_path
      end

    private
    def logi
        params.require(:employer).permit(:name, :email, :date_of_birth, :gender, :location, :phone_number, :avatar, :password, :password_confirmation)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # Restrict access so only logged in users can access the secret page:
  before_action :authorize, only: [:secret]

  def secret
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        # No need for anything in here, we are just going to render our
        # new.html.erb AKA the login page
      end
    
      def create
        # Look up employer in db by the email address submitted to the login form and
        # convert to lowercase to match email in db in case they had caps lock on:
        employer = Employer.find_by(email: params[:login][:email].downcase)
        
        # Verify employer exists in db and run has_secure_password's .authenticate() 
        # method to see if the password submitted on the login form was correct: 
        if employer && employer.authenticate(params[:login][:password]) 
          # Save the employer_id in that employer's session cookie:
          session[:employer_id] = employer.id.to_s
          redirect_to employer_index_path, notice: 'Successfully logged in!'
        else
          # if email or password incorrect, re-render login page:
          flash.now.alert = "Incorrect email or password, try again."
          render :new
        end
      end
    
      def destroy
        # delete the saved employer_id key/value from the cookie:
        session.delete(:employer_id)
        redirect_to login_path, notice: "Logged out!"
      end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def login
    user = Employer.find_by(email: params[:email])
   
    if user && user.password == params[:password]
      redirect_to employer_index_path, notice: 'Successfully logged in!'
    else
      flash[:alert] = "User not found."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employer_helper.rb
module EmployerHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/employer/edit.html.erb
<%= javascript_include_tag "login" %>
<%= stylesheet_link_tag "login" %>


<center>
  <h1>Edit Employer</h1>
</center>  

  <% if @employer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@employer.errors.count, "error") %> prohibited
        this employer from being saved:
      </h2>
      <ul>
        <% @employer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
<%= form_with(model: @employer, local: true) do |form| %>
 
  <div class="row">
  <div class="col-sm-4"></div>
  <div class="col-sm-4">

          <div class="row">
              <div class="col-sm">
                  <p>
                      <%= form.label :name %><br>
                      <%= form.text_field :name %>
                  </p>
              </div>
          
              <div class="col-sm">
                  <p>
                      <%= form.label :email %><br>
                      <%= form.email_field :email%>
                  </p>
              </div>
          </div>

          <div class="row">
              <div class="col-sm">
                  <p>
                      <%= form.label :date_of_birth %><br>
                      <%= form.text_field :date_of_birth %>
                  </p>
              </div>
      
              <div class="col-sm">
                  <p>
                      <%= form.label :gender %><br>
                      <%= form.text_field :gender %>
                  </p>
              </div>
          </div>

          <p>
              <%= form.label :location %><br>
              <%= form.text_field :location%>
          </p>
      
          <p>
              <%= form.label :phone_number %><br>
              <%= form.text_field :phone_number%>
          </p>

          <p>
            <%= form.label :avatar %><br>
            <%= form.file_field :avatar %>
          </p>

          <div class="row">
              <div class="col-sm">
                  <p>
                      <%= form.label :password %><br>
                      <%= form.password_field :password %>
                  </p>
              </div>

              <div class="col-sm">
                  <p>
                      <%= form.label :password_confirmation %><br>
                      <%= form.password_field :password_confirmation %>
                  </p>
              </div>
          </div>
      
          <center>
              <p>
                  <%= form.submit %>
              </p>
          </center>
          <div class="col-sm-4"></div>
<% end %>
 
<br><br><br>
<center>
<%= link_to 'Back', employer_index_path %>
</center>

app/views/employer/index.html.erb
<%= javascript_include_tag "login" %>
<style>
  html{
    overflow: unset;
  }
  td{
    border-bottom: 1px solid black;
  }
</style>

<div class="container-fluid">
  <center>
    <h1>Employer's List</h1>
  </center> 

  <br><br>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <tr class="thead-dark">
          <th>Name</th>
          <th>E-mail</th>
          <th>Date of birth</th>
          <th>Gender</th>
          <th>Location</th>
          <th>Phone number</th>
          <th colspan="3">Extras</th>
        </tr>
      </tr>
    </thead>
    <tbody>
    <% @employer.each do |employer| %>
      <tr style="font-size: large;">
        <td><%= employer.name %></td>
        <td><%= employer.email %></td>
        <td><%= employer.date_of_birth %></td>
        <td><%= employer.gender %></td>
        <td><%= employer.location %></td>
        <td><%= employer.phone_number %></td>
        <td><%= link_to 'Show', employer_path(employer) %></td>
        <td><%= link_to 'Edit', edit_employer_path(employer) %></td>
        <td><%= link_to 'Delete', employer_path(employer), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br><br><br>
  <center>
      <%= link_to 'Register', new_employer_path %>
      &nbsp
      <%= link_to 'Home', welcome_index_path %>
      &nbsp
      <a href="/logout">Logout</a>
  </center>
</div>

app/views/employer/new.html.erb
<%= javascript_include_tag "login" %>
<%= stylesheet_link_tag "login" %>

<center>
    <h1>Register</h1>
</center>

<ul>
<% if !! flash[:errors] %>

<% flash[:errors].each do |error| %>
    <li><%= error %></li>
    <% end %>
    <% end %>
</ul>

<div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
        <%= form_with scope: :employer, url: employer_index_path, validate: true, local: true do |form| %>

            <div class="row">
                <div class="col-sm">
                    <p>
                        <%= form.label :name %><br>
                        <%= form.text_field :name, required: true %>
                    </p>
                </div>
            
                <div class="col-sm">
                    <p>
                        <%= form.label :email %><br>
                        <%= form.email_field :email, required: true %>
                    </p>
                </div>
            </div>

            <div class="row">
                <div class="col-sm">
                    <p>
                        <%= form.label :date_of_birth %><br>
                        <%= form.date_field :date_of_birth %>
                    </p>
                </div>
        
                <div class="col-sm">
                    <p>
                        <%= form.label :gender %><br>
                        <%= form.text_field :gender %>
                    </p>
                </div>
            </div>

            <p>
                <%= form.label :location %><br>
                <%= form.text_field :location, required: true %>
            </p>
        
            <p>
                <%= form.label :phone_number %><br>
                <%= form.text_field :phone_number, required: true %>
            </p>

            <p>
                <%= form.label :avatar %><br>
                <%= form.file_field :avatar %>
            </p>

            <div class="row">
                <div class="col-sm">
                    <p>
                        <%= form.label :password %><br>
                        <%= form.password_field :password, required: true %>
                    </p>
                </div>

                <div class="col-sm">
                    <p>
                        <%= form.label :password_confirmation %><br>
                        <%= form.password_field :password_confirmation, required: true %>
                    </p>
                </div>
            </div>
        
            <center>
                <p>
                    <%= form.submit %>
                </p>
            </center>
        <% end %>
    </div>
    <div class="col-sm-4"></div>
</div>

<br><br><br>
<center>
<%= link_to 'Back', welcome_index_path %>
</center>

app/views/employer/show.html.erb
<%= javascript_include_tag "login" %>
<style>
  p{
    font-size: large;
  }
  img{
    border-radius: 10px;
  }
  @media (max-width: 600px){
    .row{
      flex-direction: column-reverse;
    }
  }
</style>

<div class="container">
  <center>
    <h1>Your Profile</h1>
  </center>

  <br><br><br>

  <div class="row">
  <div class="col-sm">
  <p>
    <strong>Name:</strong>
    <%= @employer.name %>
  </p>
  
  <p>
    <strong>E-mail:</strong>
    <%= @employer.email %>
  </p>

  <p>
    <strong>Date of birth:</strong>
    <%= @employer.date_of_birth %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= @employer.gender %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= @employer.location %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= @employer.phone_number %>
  </p>
  </div>

  
  <div class="col-sm">
  <div class="images"></div>
  <%= image_tag @employer.avatar.variant(resize_to_limit: [300, 300]) %>
  </div>
  </div>

  <br><br><br><br>

  <center>
      <%= link_to 'Back', new_employer_path %>
      &nbsp
      <%= link_to 'Table', employer_index_path %>
      &nbsp
      <%= link_to 'Home', welcome_index_path %>
  </center>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <meta name="viewport" content="width=device-width initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
        html{
          overflow: hidden;
          height: 100%;
        }
        body{
          overflow-x: hidden;
          height: 100%;
        }
    </style>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">BlOg</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active nav-link">
      <% if current_user %>
      <!-- current_user will return true if a user is logged in -->
      <%= "Logged in as #{current_user.name}" %> | <%= link_to 'Home', root_path %> | <%= link_to 'Log Out', logout_path, method: :get %>
    <% else %>

      </li>
      <li class="nav-item nav-link">
      <!-- not logged in -->
      <%= link_to 'Home', root_path %> | <%= link_to 'Log In', login_path %> or <%= link_to 'Sign Up', new_employer_path %>
    <% end %>
      </li>
    </ul>
  </div>
</nav>
<br><br>

    <%= yield %>
  </body>
</html>

app/views/pages/secret.html.erb
<h1>Pages#secret</h1>
<p>Find me in app/views/pages/secret.html.erb</p>

app/views/welcome/index.html.erb
<%= javascript_include_tag "login" %>
<%= javascript_include_tag "application" %>
<div class="container-fluid">
<center><h1>Welcome</h1></center>

<br><br><br><br>

<!-- Button trigger modal -->
<center><button type="button" class="btn btn-info" data-toggle="modal" data-target="#Modal"> CHOOSE </button></center>

<!-- Modal -->
<div class="modal fade" id="Modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <center>
        <a href="/login">Login</a>
        <br><br>
        <p>
          <%= link_to 'Register', new_employer_path %>
        </p>
      </center>
      </div>
    </div>
  </div>
</div>
</div>